AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
Style:
  Enabled: false

Metrics:
  Enabled: false
    
Layout:
  Enabled: false

Naming:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Lint/ConstantDefinitionInBlock:
    Enabled: true
    Exclude:
      - 'spec/**/*.rb'
Lint/UselessAssignment:
    Enabled: false
Lint/EmptyBlock:
    Enabled: false
Lint/ReturnInVoidContext:
    Enabled: false
Lint/AssignmentInCondition:
    Enabled: false
Lint/AmbiguousBlockAssociation:
    Enabled: false
Security/Eval:
    Enabled: false
Lint/MissingSuper:
    Enabled: false
