# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'procon_bypass_man', '0.3.10'

# uncomment if you want to use master branch
# gem 'procon_bypass_man', github: 'splaplapla/procon_bypass_man', branch: 'master'
# uncomment if you want to use serial communication feature
# gem "serialport"
