#!/usr/bin/env ruby

gem_root = Gem::Specification.find_by_name("procon_bypass_man").gem_dir
system("mkdir -p pbm_project")
system("cp -r #{gem_root}/examples/recommend/* pbm_project")
system("cp -r #{gem_root}/examples/recommend/* pbm_project")

project_path = File.expand_path('.', __FILE__)
File.write "#{project_path}/setup.sh", "sudo ln -s /systemd_units/pbm.service /etc/systemd/system/pbm.service"
