#!/usr/bin/env ruby

require "erb"

def project_dir
  "pbm_project"
end

def current_dir
  Dir.pwd
end

def app_bin_path
  "#{current_dir}/#{project_dir}/app.rb"
end

gem_root = Gem::Specification.find_by_name("procon_bypass_man").gem_dir

system("mkdir -p #{project_dir}")
system("cp #{gem_root}/project_template/systemd_units/pbm.service.erb #{project_dir}/systemd_units/pbm.service.erb")
system("cp #{gem_root}/project_template/app.rb #{project_dir}/app.rb")
system("cp #{gem_root}/project_template/setting.yml #{project_dir}/setting.yml")

File.write "#{project_dir}/setup.sh", "sudo ln -s #{current_dir}/#{project_dir}/systemd_units/pbm.service /etc/systemd/system/pbm.service"

valid_pbm_service_body = ERB.new(
  File.read("#{current_dir}/#{project_dir}/systemd_units/pbm.service.erb")
).result
File.write("#{current_dir}/#{project_dir}/systemd_units/pbm.service", valid_pbm_service_body)
