#!/usr/bin/env ruby

require "bundler/setup"
require "procon_bypass_man"

begin
  pid = File.read(ProconBypassMan.pid_path).chomp
  Process.kill("TERM", pid)
  exit 0
rescue Errno::ENOENT => e
  puts e
  exit 1
end
